#!/bin/bash
if [ $# -eq 2 ];then
	event=$1
	message=$2
	id=$(cat "/opt/user/config/instapush/instapush.json"|getJson id)
	secret=$(cat "/opt/user/config/instapush/instapush.json"|getJson secret)

	/show/listecho "Send $message -> $event"
	curl -X POST \
    	       -H "x-instapush-appid: $id" \
    	       -H "x-instapush-appsecret: $secret" \
                    -H "Content-Type: application/json" \
                    -d "{\"event\":\"$event\",\"trackers\":{\"message\":\"$message\"}}" \
                    https://api.instapush.im/post
else
	/show/errorBox "Wrong number of arguments"
	/show/usage '/do/instapush/send event message'
	/show/example '/do/instapush/send "MyInstaPushEvent" "This is a test"' 
fi
